#!/bin/bash
SSV_DRV_PATH=$PWD
KERNEL_OBJ_PATH=/home/wh/SDK/ISVP-T40-1.1.1-20220120/software/sdk/Ingenic-SDK-T40-1.1.1-20220120/opensource/kernel-4.4.94
INSTALL_PATH=/home/wh/Downloads/L.SMAC.19Q3.2220.01-K300/build
PLATFORM_TOOLCHAIN=mips-linux-gnu-
PLATFORM_ARCH=mips

make -C $SSV_DRV_PATH KERNEL_OBJ_PATH=$KERNEL_OBJ_PATH SSV_DRV_PATH=$SSV_DRV_PATH ARCH=$PLATFORM_ARCH CROSS_COMPILE=$PLATFORM_TOOLCHAIN clean
make -C $SSV_DRV_PATH KERNEL_OBJ_PATH=$KERNEL_OBJ_PATH SSV_DRV_PATH=$SSV_DRV_PATH ARCH=$PLATFORM_ARCH CROSS_COMPILE=$PLATFORM_TOOLCHAIN modules
make -C $SSV_DRV_PATH SSV_DRV_PATH=$SSV_DRV_PATH CROSS_COMPILE=$PLATFORM_TOOLCHAIN strip
make -C $SSV_DRV_PATH KERNEL_OBJ_PATH=$KERNEL_OBJ_PATH SSV_DRV_PATH=$SSV_DRV_PATH INSTALL_PATH=$INSTALL_PATH install
